WIP: Dockerization du projet
lairdubois/lairdubois pull request #68
Opened 2020-12-21 13:17 UTC by lobodol

Bonjour les dev-boiseux,

J'ai voulu installer le projet en local et en lisant la doc je me suis rendu compte que c'était assez complexe, qu'il fallait installer pas mal de choses et que j'avais pas forcément envie d'installer tout ça sur ma machine.

C'est pourquoi je me suis mis en tête de "Dockeriser" le projet afin d'en simplifier l'installation locale.

Le but de la manoeuvre étant d'arriver à une procédure d'installation hyper simple sans avoir à se soucier de l'installation de tous les services (Elasticsearch, RabitMQ, php-fpm, etc).

Je pense que ça permettrait de rendre plus accessible la participation des dev.

Est-ce que c'est quelque chose qui vous intéresse ?

Bonne journée

PS: WIP = Work in Progress

2020-12-21 13:39 UTC, lobodol commented
Reste à faire :

* [ ] Documentation d'installation avec Docker
* [ ] Container [Maildev](https://hub.docker.com/r/maildev/maildev)
* [ ] The RabbitMQ webpush notification consumer
* [ ] The RabbitMQ view consumer
* [ ] The Workflow web socket server
* [ ] Build assets
* [ ] ...

2020-12-21 13:55 UTC, lobodol commented
Linked issue #69

2020-12-21 16:39 UTC, bbeaulant commented
Salut, merci pour cette initiative. Mais le soucis que j'y vois sur le long terme, est le même que d'utiliser [ansible](https://github.com/lairdubois/lairdubois-ansible), cie, c'est qu'il faut aussi le maintenir dans le temps. C'est une tâche qui ne peut pas être ponctuelle. Et dans la vie d'un projet bénévole, moins il y a de doublon à maintenir, mieux c'est :)

La procédure plate est certes lourde, mais à la mérite d'être complète et fidèle à la prod et bien plus facile à maintenir.

L'option de monter une VM évite d'installer tout ça sur le poste de DEV.

2020-12-22 11:02 UTC, lobodol commented
Ansible c'est pour le déploiement en production, là je voyais plus la partie Docker pour les dev, avec tous les outils qui vont bien. Genre Xdebug par exemple. Ce dernier n'a pas de raison de se trouver en prod alors qu'il a sa place en environnement de dev.
Maintenant c'est vrai que ça fait plusieurs choses à maintenir. Cependant, si les dev utilisent principalement la version "Dockerisée" on se rendra vite compte si une conf n'est pas à jour ou s'il y a un bug. Mais je comprends, ça rajoute une stack technique.

Pour le coup, je suis contre les VM, c'est très lourd et ça ne garantit pas la répétabilité des process. Si j'ai fait de la m*rde dans un container, j'ai juste à le kill et le remonter. Si j'ai foutu en l'air ma VM, je suis bon pour tout réinstaller à la main...
Selon moi, le gros avantage des containers est qu'ils sont jetables et remontables à l'infini avec la garantie qu'ils soient identiques.

Qu'en dis-tu ?

2020-12-22 11:13 UTC, bbeaulant commented
Salut,

J'en pense que jusqu'ici le problème ne s'est jamais posé, parce que je suis le seul dev depuis 8 ans et que pour des raisons de perf tous les outils sont installés en local pour ma part.
Après, de plus en plus de motivés essayent de venir en aide au projet. Mais il est certain que la procédure d'installation en rebute plus d'un.
En l'état, c'est certain qu'une simplification des moyen pour monter une station de dev serait intéressante. MAIS ... dans le seul cas où c'est maintenu et utilisable sur n'importe quel OS avec exactement la même procédure.

Je ne connais pas assez Docker pour avoir un avis tranché. Je sais juste que mettre la procédure et ne pas la maintenir peut sur le long terme de faire perdre du temps aux permanants.

Après, je suis ouvert à apprendre là dessus dans la limite où c'est pas une usine à gaz comme ansible. Ici les besoins sont hyper limité. Par contre, les outils sont nombreux et avec des configs à la con. Et même si je n'ai que l'XP de la VM et bien au moins elle peut être en tout point identique à la PROD.

Le temps passer ici coute cher. Et l'expérience me fait préférer ce qui marche et est maitriser à ce qui serait tip top, mais plus délicat à maitriser sur le long terme.

Pour résumé, disposer à essayer avec la solution Docker, mais à valider si c'est viable sur le long terme de maintenir sans celui qui l'a créé.

2020-12-22 11:25 UTC, bbeaulant commented
Sinon, petite question curieuse : Qu'est-ce qui te motive à apporter ton soutient à ce projet ?

2020-12-22 11:35 UTC, lobodol commented
> Sinon, petite question curieuse : Qu'est-ce qui te motive à apporter ton soutient à ce projet ?

Comme tout passionné du travail du bois j'ai fini par tomber sur lairdubois.fr. En m'y promenant j'ai vu que le projet était open source et en plus sur un techno que j'affectionne : Symfony. \
Le travail réalisé est juste oufissime et je serais ravis de participer à améliorer cette plateforme :)

2020-12-22 11:44 UTC, lobodol commented
Pour l'argument "utilisable sur n'importe quel OS" ça va pas être possible avec Windows... Sous MacOS je crois que c'est possible mais j'ai jamais testé.

Après il faut voir ça comme du plus. Ça n'empêchera jamais la prod de tourner. 

Personnellement, j'utilise Docker tous les jours dans mon taf et même pour la prod (conjointement avec Kubernetes). Après ça demande un temps de montée en compétence, faut pas se mentir.

>  dans la limite où c'est pas une usine à gaz comme ansible

Qu'est-ce qui te fait dire qu'Ansible est une usine à gaz ? C'est parfait pour gérer des déploiements d'après moi.

>  Par contre, les outils sont nombreux et avec des configs à la con

Le gros avantage là serait d'avoir tout centralisé au même endroit et surtout de ne même pas avoir à s'en soucier.

Dans ce cas, je vais terminer ma PR et je te laisserai essayer.

2020-12-22 11:53 UTC, bbeaulant commented
> ça va pas être possible avec Windows... Sous MacOS je crois que c'est possible mais j'ai jamais testé.

Hmm, je pense que ça limite vraiment l'intérêt alors. Parce que 90% de ceux qui ont essayé de s'y lancé étaient sous Win ou Mac.

> Après il faut voir ça comme du plus. Ça n'empêchera jamais la prod de tourner.

On est d'accord. Mais c'est comme garder une doc ça n'a d'intérêt que si c'est à jour.
Et quand je vois le temps que je passe à échanger pour résoudre le pb d'installations de ceux qui essayent, je me dis que le seul outil qui peut vraiment être intéressant est un outil indépendant de l'OS hôte.

> Qu'est-ce qui te fait dire qu'Ansible est une usine à gaz ?

Dans le cas d'usage LADB, c'est bien trop "complexe" pour faire des choses simples. Mais on est d'accord que c'est pas non plus fait pour du monoserveur qu'on re-installe tous les 2ans :)

> Le gros avantage là serait d'avoir tout centralisé au même endroit et surtout de ne même pas avoir à s'en soucier.

Si et seulement si ça peut fonctionner pour tout le monde de la même façon. Mais la blocage windows que tu pointes en premier me laisser interrogatif.
Qu'est-ce qui fait que ça ne fonctionnerait pas sur Windows ?

2020-12-23 11:03 UTC, lobodol commented
Il semblerait que Docker soit finalement fonctionnel sous Windows. Je viens de tester et ça marche à peu près. À peu près car il y a quand même quelques adaptations à faire...
Perso je vois plus ça comme du bonus : ceux qui ont Docker et savent s'en servir peuvent utiliser cette procédure. Les autres font avec la procédure standard.

Tu fais combien de déploiements par an à la louche ?

Mais je comprends, si tu es le seul dev réellement actif et que tu ne maîtrises pas Docker c'est peut-être risqué de mettre ça en place.

Quoi qu'il en soit je garde cette config pour moi car elle me convient bien, elle reste dispo sur mon fork.

2020-12-23 11:09 UTC, bbeaulant commented
> Il semblerait que Docker soit finalement fonctionnel sous Windows. Je viens de tester et ça marche à peu près.

C'est déjà plus rassurant :)

> Tu fais combien de déploiements par an à la louche ?

Haha, c'est très variable. Le projet évolue au gré des envies et temps disponible pour le faire. Mais globalement on doit être à 5-10 gros déploiement par an et une grosse 50ène de petites modifs à déployer.

> Mais je comprends, si tu es le seul dev réellement actif et que tu ne maîtrises pas Docker c'est peut-être risqué de mettre ça en place.

Peut être est-ce que ça peut être un autre repository un peut comme le repo ansible (qui n'est pas à jour, par contre). Un truc genre lairdubois/lairdubois-docker ... et à toi de le maintenir et le documenter ou d'aider le/les devs à savoir quoi changer pour que ça puisse évoluer si on a besoin de changer des libs ou app externes.

2020-12-31 11:22 UTC, lobodol commented
Salut,
Oui, ça pourrait être une solution d'avoir ça dans un répo à part. Je te tiendrai au courant de mon avancement, pour l'instant tous les services ne sont pas encore opérationnels. Une fois que tout fonctionnera on pourra voir pour coller tout ça dans un répo dédié.

2021-03-09 06:44 UTC, agrarian-systems commented
Salut Lobodol, ok pour t'aider sur le Docker. Je suis sur Mac et je vais être obligé de faire une VM dans tous les cas si je veux contribuer au projet ADB ;) On peut essayer de voir ce que ça donne ensemble ;)

2021-03-10 10:56 UTC, lobodol commented
Salut @agrarian-systems, avec joie !

2021-03-10 20:36 UTC, bbeaulant commented
Super les gars,

Si vous arrivez à un truc propre, idéalement, il faudrait que ça soit multi-système (Linux, Win et Mac) et dans ce cas, on pourra faire un nouveau repo pour ça sous l'orga lairdubois.
Le repo principal ne contiendra pas la procédure Docker. Trop contraignant à maintenir.

2021-03-11 13:09 UTC, lobodol commented
Yes, c'est noté.

Pour info, j'arrive à faire tourner l'app mais j'ai quand-même un souci avec la construction des assets avec AsseticBundle. Pour une raison que j'ignore, les menus de navigation `ladb_topbar`, `ladb_bottombar` et `ladb_leftbar` sont pétés :

![adb](https://user-images.githubusercontent.com/7249581/110792009-2ba4c280-8273-11eb-8fa8-cb357ceea7e7.png)

Pourtant, aucune erreur lors de l'exécution des commandes `bin/console assetic:dump` et `bin/console assets:install`.

Une idée @bbeaulant ?

2021-03-11 13:34 UTC, bbeaulant commented
Y a que ces menus là qui n'ont pas leur style ?
Il ressemble à quoi le reste du site ? (Capture ?)

2021-03-11 14:33 UTC, lobodol commented
> Y a que ces menus là qui n'ont pas leur style ?

Oui, il semblerait que seuls ces menus soient KO. Le reste du site à l'air normal, quoi que ça reste relativement difficile à estimer vu que je n'ai pas de données en BDD.

2021-03-11 17:33 UTC, bbeaulant commented
Faudrait regarder dans la console du navigateur pour savoir s'il n'y a pas des fichiers css qu'il ne parvient pas à charger.

2021-03-11 17:36 UTC, lobodol commented
Non, tout va bien de ce côté-là, tous les assets sont correctement chargés par le navigateur (que des statusCode 200).

2021-03-11 17:42 UTC, bbeaulant commented
Tu tournes en environnement dev ou prod pour SF ?
Sans plus de log ou autre trucs visibles, je peux pas plus te renseigner. Je vois pas pkoi il y aurait que cette partir qui ne serait pas compilé. C'est dans le même groupe de fichiers LESS.

> Quelle version exacte de NodeJS utilises-tu ?

NodeJS ne doit pas dépasser la version 10.x. Sinon c'est pas compatible avec Assetic. Comme je l'ai écrit dans la [doc d'installation](https://github.com/lairdubois/lairdubois/blob/master/docs/01-installation.md).

![Capture d’écran 2021-03-11 à 18 41 27](https://user-images.githubusercontent.com/156056/110830376-71748180-8299-11eb-96ed-d51af7a2ea71.png)

2021-03-11 17:52 UTC, lobodol commented
> Tu tournes en environnement dev ou prod pour SF ?

Je tourne en environnement de dev. J'ai essayé également avec l'environement de prod mais je constate le même problème.

> NodeJS ne doit pas dépasser la version 10.x

Yep, c'est bien ce que j'ai fait dans le `Dockerfile` :
![node_version](https://user-images.githubusercontent.com/7249581/110830870-f5c70480-8299-11eb-8a61-bc9cc71444fb.jpg)

C'est pour ça que je te demandais la version précise que tu utilises pour voir si d'une sous version à une autre il n'y a pas un changement de comportement.

Par contre je n'avais pas vu [ce commit](https://github.com/lairdubois/lairdubois/commit/12cba2fcbe66fc2bf6934e710dcbaca97553bf9c). Jusque là je faisais comme avant ce commit, à savoir `npm install -g less`. Je vais essayer avec la contrainte de version, peut-être que ça résoudra le problème. Je te tiens au courant.

Autre question : je vois des références à java dans la conf d'Assetic ; y a-t-il besoin d'installer un JDK/JRE quelconque ? Je n'ai rien vue en ce sens dans la doc d'installation.

2021-03-11 17:57 UTC, bbeaulant commented
`NodeJS 10.24.0`

> je vois des références à java dans la conf d'Assetic ; y a-t-il besoin d'installer un JDK/JRE quelconque ? Je n'ai rien vue en ce sens dans la doc d'installation.

Oui, pour `closure` et `yui_css`. Mais je n'ai jamais vu encore de pb de version de la JRE par rapport à ça.

https://github.com/lairdubois/lairdubois/blob/f890714850d56c9a833c3e38570544f690003483/app/config/config.yml#L66

2021-03-11 18:15 UTC, lobodol commented
> `NodeJS 10.24.0`

Alleluia c'était bien ça !

2021-03-11 19:45 UTC, agrarian-systems commented
Tu avances à toute vitesse c'est chouette. Je n'ai pas du tout eu le temps de m'y plonger mais si tu as des besoins de coups de main n'hésite pas ;)

2021-04-28 06:58 UTC, manooweb commented
Hello,
Sous windows, cela a un peu évolué côté docker mais je n'avais pas trouvé de bonne solution pour activer le nécessaire.
Le plus simple pour être sûr que cela fonctionne est d'avoir un Win10Pro qui a tous les prérequis pour Docker Desktop mais il semblerait que cela a évolué depuis si je me réfère à la [documentation](https://docs.docker.com/docker-for-windows/install/)

Avec l'arrivée de WSL2 (Windows Subsytem Linux), cela permet d'avoir des containers Docker linux donc plus proche de la réalité de production qu'un container Windows.
J'utilise WSL2 en stand alone pour le moment avec une distribution Ubuntu 20.04 et je trouve çà assez pratique pour faire des tests complémentaires dans mon travail.

Si vous avez besoin d'un testeur sur cet OS, je serai ravi de pouvoir essayer/aider une fois que la documentation d'installation sera prête à moins qu'il soit déjà possible d'avoir un how to simple et rapide pour faire des premiers essais.

++

2021-04-29 12:44 UTC, lobodol commented
Hello @manooweb,
Yes je suis preneur pour tester la stack sous Windows car je ne tourne que sous Linux. Mais normalement, il ne devrait pas y avoir de problème :)

2021-04-29 14:14 UTC, manooweb commented
> Hello @manooweb,
> Yes je suis preneur pour tester la stack sous Windows car je ne tourne que sous Linux. Mais normalement, il ne devrait pas y avoir de problème :)

Pas de problème, je suis un peu comme Boris avec une stack à l'ancienne où j'y ai des habitudes et pas avec trop de compétence sur Docker mais je vois bien sur d'autre projet que çà facilite la contribution en ayant un environnement opérationnel rapidement car automatisé. Ceci étant sous Windows on a quelque fois quelques surprises et c'est pour cela que je cherche des solutions pour me faciliter la vie et que j'ai donc commencé à m'intéresser à WSL2. J'ai donc un Ubuntun 20.04 plutôt opérationnel - j'y installe les packages au fur et à mesure de mes besoins. Côté Docker je viens de faire la dernière mise à jour.

Je devrais donc avoir les éléments pour faire au moins un premier test avec cet OS

2021-06-03 09:16 UTC, lobodol commented
Salut @bbeaulant, pourrais-tu me communiquer la version exacte de MariDB utilisée en prod stp ? (en commentaire ici ou par mail si tu préfères)

2021-06-17 08:53 UTC, lobodol commented
Bonjour à tous,

Je pense qu'en l'état, le projet est testable. Tout n'est pas encore opérationnel (websocket & queue notamment) mais ça permet au moins de charger l'application et de l'utiliser.

Une seule commande à taper pour initialiser le projet :

```bash
make start
```
(détail de la commande dans le fichier `Makefile`).

Cette commande va :
* démarrer les containers
* installer les dépendances PHP
* installer les assets
* initialiser les BDD
* alimenter ElasticSearch

Reste à mettre à jour votre fichier `hosts` :

```
127.0.0.1 dev.lairdubois.fr
```

Les mails sont catchés par Maildev et visibles sur http://127.0.0.1:1080
Pensez donc à mettre à jour votre fichier `parameters.yaml` :

```yaml
#parameters.yml
  mailer_host: mail # le nom du service déclaré dans docker-compose.yml
```

2021-06-17 13:32 UTC, manooweb commented
d'ac merci.
Comme convenu je testerai sous Windows 10 Pro

2021-11-01 21:23 UTC, Pierstoval requested changes
J'ai fait quelques demandes de changement, car un setup un peu similaire est présent sur la branche `migration-sf5`.
J'utilise Windows 10 + WSL 2, et j'ai testé ces changements, et ça fonctionne :)

2021-11-01 21:23 UTC, Pierstoval commented on .docker/server/dev.lairdubois.fr.conf
> +    server_name             dev.lairdubois.fr;
Il faut d'autres noms de domaines. Il n'est pas acceptable d'associer un domaine en `.fr` sur une machine locale 😕

Par convention, certains outils utilisent `.wip` ou `.docker` (j'utilise le dernier) et les devs modifient les hosts de leur machine pour faire pointer ces domaines personnalisés vers `127.0.0.1` (je fais ça aussi).

2021-11-01 21:23 UTC, Pierstoval commented on Makefile
> +start: ## Initialize project & start all containers
Par convention, on utilise plutôt `install`.

`start` sera plutôt là pour faire un simple `docker-compose up -d` 😉

2021-11-01 21:23 UTC, Pierstoval commented on docker-compose.yml
> +      - 80:80
Exposer le port 80 peut entrer en conflit avec d'autres applis. Par convention dans l'écosystème PHP on expose plutôt le port 8000. (pour info, en Ruby on expose souvent le port 4000, et avec Node.js le port 3000)

2021-11-01 21:23 UTC, Pierstoval commented on docker-compose.yml
> +      - 1025:25
Pas besoin d'exposer ce port 1025, c'est le serveur SMTP, et il ne devrait être utilisé que par l'appli PHP

2021-11-01 21:23 UTC, Pierstoval commented on .gitignore
> +.DS_Store
Ce genre de dossier ne devrait même jamais être présent dans le `.gitignore` d'un projet, et à la place être ignoré globalement sur toute la machine.

Un peu de doc sur comment faire : https://stackoverflow.com/a/7335487/1697192

2021-11-02 07:59 UTC, bbeaulant commented
Merci @Pierstoval, mais en effet, cette PR va devenir obsolète. La migration SF5 étant devenue indispensable pour continuer de maintenir le projet. Donc, il est préférable à cette heure de travailler sur la branche https://github.com/lairdubois/lairdubois/tree/migration-sf5

2021-11-02 15:08 UTC, lobodol commented on .gitignore
> +.DS_Store
Je suis bien d'accord, j'avais proposé une PR il y a quelques mois, mais on m'a répondu que c'était comme ça.

2021-11-02 16:02 UTC, bbeaulant commented on .gitignore
> +.DS_Store
Haaa ... des puristes qui titillent 😘

2021-11-02 17:55 UTC, Pierstoval commented
N'hésite pas à fermer la PR pour éviter qu'il n'y ait d'autresd review 😁😁

2021-11-03 14:03 UTC, lobodol commented
Je ferme cette PR en faveur de https://github.com/lairdubois/lairdubois/tree/migration-sf5

2021-11-03 14:03 UTC, closed without merging

2021-11-03 14:16 UTC, bbeaulant commented
Merci beaucoup @lobodol pour la base que tu as posé et qui a été utilisé pour la suite !